import {
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  BrainCircuit,
  Code2,
  Copy,
  Database,
  ExternalLink,
  FileDown,
  Github,
  Globe,
  GraduationCap,
  HeartHandshake,
  LayoutGrid,
  Mail,
  MonitorSmartphone,
  Rocket,
  Search,
  Server,
  Send,
  Sparkles,
  TerminalSquare,
  Youtube,
  type LucideIcon,
  Palette,
  GitBranch,
  Wind,
  Boxes,
  Laptop,
  Layers3,
  Type,
  FolderKanban,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  arrowRight: ArrowRight,
  badgeCheck: BadgeCheck,
  brain: BrainCircuit,
  code: Code2,
  copy: Copy,
  database: Database,
  externalLink: ExternalLink,
  fileDown: FileDown,
  github: Github,
  globe: Globe,
  graduationCap: GraduationCap,
  handshake: HeartHandshake,
  grid: LayoutGrid,
  mail: Mail,
  mobile: MonitorSmartphone,
  rocket: Rocket,
  search: Search,
  server: Server,
  send: Send,
  sparkles: Sparkles,
  terminal: TerminalSquare,
  youtube: Youtube,
  palette: Palette,
  git: GitBranch,
  wind: Wind,
  boxes: Boxes,
  laptop: Laptop,
  layers: Layers3,
  type: Type,
  folder: FolderKanban,
  react: Code2,
  "next.js": Rocket,
  nextjs: Rocket,
  typescript: Type,
  tailwind: Wind,
  "tailwind css": Wind,
  postgresql: Database,
  "node.js": Server,
  nodejs: Server,
  prisma: Layers3,
  docker: Boxes,
  vitest: BadgeCheck,
  storybook: LayoutGrid,
  indexeddb: Database,
  html: Code2,
  css: Palette,
  javascript: Code2,
  figma: Palette,
  zod: BadgeCheck,
  rest: Globe,
  "rest apis": Globe,
  arrowleft: ArrowLeft,
  "framer motion": Sparkles,
  "framer-motion": Sparkles,
};
